services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: |
      bun install
      bunx puppeteer browsers install chrome
    startCommand: bun start
    autoDeploy: true
