services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: IDLE_TIMEOUT
        value: 180000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
