services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
      ls -la /opt/render/.cache/puppeteer/chrome/
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: IDLE_TIMEOUT
        value: 180000
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
