services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: |
      bun install
      bunx puppeteer browsers install chrome
      CHROME_PATH=$(find /opt/render/.cache/puppeteer -name chrome -type f | head -1)
      echo "Chrome path: $CHROME_PATH"
      echo "PUPPETEER_EXECUTABLE_PATH=$CHROME_PATH" >> $ENV_FILE
    startCommand: bun start
    autoDeploy: true
