services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: |
      echo "=== Setting up Puppeteer Cache Directory ==="
      mkdir -p /opt/render/.cache/puppeteer
      export PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer
      echo "Cache directory: $PUPPETEER_CACHE_DIR"

      echo "=== Installing Dependencies ==="
      npm install

      echo "=== Attempting to install system Chromium (fallback) ==="
      apt-get update && apt-get install -y chromium-browser || echo "System Chromium installation failed, using Puppeteer bundled version"

      echo "=== Installing Puppeteer Chromium ==="
      PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer npx puppeteer browsers install chrome || echo "Puppeteer browser installation failed"

      echo "=== Verifying Installation ==="
      ls -la /opt/render/.cache/puppeteer/chrome/ 2>/dev/null || echo "Chrome directory not found"
      find /opt/render/.cache/puppeteer/ -name "chrome" -type f 2>/dev/null || echo "Chrome binary not found"
      which chromium-browser 2>/dev/null || echo "System chromium-browser not found"

      echo "=== Build Complete ==="
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: BROWSER_POOL_SIZE
        value: 1
      - key: MAX_CONCURRENT_REQUESTS
        value: 2
      - key: PAGE_LOAD_TIMEOUT
        value: 60000
      - key: IDLE_TIMEOUT
        value: 1800000
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
