services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: |
      echo "=== Installing Puppeteer Chromium ==="
      npm install
      npx puppeteer browsers install chrome
      echo "=== Chromium Installation Complete ==="
      echo "=== Checking installed browsers ==="
      ls -la $HOME/.cache/puppeteer/ 2>/dev/null || echo "Puppeteer cache not found"
      echo "=== Build Complete ==="
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: BROWSER_POOL_SIZE
        value: 1
      - key: MAX_CONCURRENT_REQUESTS
        value: 2
      - key: PAGE_LOAD_TIMEOUT
        value: 60000
      - key: IDLE_TIMEOUT
        value: 1800000
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
