services:
  - type: web
    name: screenshot-api
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser
      npm install
      echo "=== System Chrome Check ==="
      which chromium-browser || echo "Chromium not found"
      ls -la /usr/bin/chromium* 2>/dev/null || echo "No chromium binaries"
      echo "=== End Check ==="
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: IDLE_TIMEOUT
        value: 180000
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
